# Generated by Django 2.2.28 on 2026-03-13 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reciperate_app', '0002_auto_20260312_1507'),
        ('reciperate_app', '0002_auto_20260312_1540'),
    ]

    operations = [
    ]
